name: ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.4.0
  flutter_staggered_grid_view: ^0.6.2


flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/crown.png"
  min_sdk_android: 16
  remove_alpha_ios: true